default: bruno knossos obsidian steam steam-native vivaldi-stable vivaldi-stable-alt steam-games update-cache

[private]
prepare FILE TARGET="":
    -cp "/usr/share/applications/{{FILE}}.desktop" "{{ if TARGET == '' { FILE } else { TARGET } }}.desktop"

[private]
add_args FILE +ARGS:
    -sed -i 's/^\(Exec=.*\)/\1 {{ARGS}}/g' "{{FILE}}.desktop"

[private]
add_runner FILE +RUNNER:
    -sed -i /$(basename "{{RUNNER}}")/'!s!^Exec=\(.*\)!Exec={{RUNNER}} \1!g' "{{FILE}}.desktop"

[private]
add_name FILE +ARGS:
    -sed -i 's/^\(Name=.*\)/\1 {{ARGS}}/g' "{{FILE}}.desktop"

[private]
electron_wayland FILE:
    just add_runner "{{FILE}}" "${HOME}/bin/electron-wayland"

[private]
electron_scaling FILE:
    just add_args "{{FILE}}" --force-device-scale-factor=1.25

bruno: (prepare "bruno")
    just electron_wayland bruno

knossos: (prepare "knossos")
    -which prime-run &>/dev/null && just add_runner knossos prime-run || rm knossos.desktop

obsidian: (prepare "obsidian")
    just electron_wayland obsidian

steam: (prepare "steam")
    -which prime-run &>/dev/null && just add_runner steam prime-run || rm steam.desktop

steam-native: (prepare "steam-native")
    -which prime-run &>/dev/null && just add_runner steam-native prime-run || rm steam-native.desktop

vivaldi-stable: (prepare "vivaldi-stable")
    sed -i "s!/usr/bin/vivaldi-stable!${HOME}/bin/vivaldi-stable!g" vivaldi-stable.desktop
    just electron_wayland vivaldi-stable

vivaldi-stable-alt: (prepare "vivaldi-stable" "vivaldi-stable-alt")
    sed -i "s!/usr/bin/vivaldi-stable!${HOME}/bin/vivaldi-stable!g" vivaldi-stable-alt.desktop
    just electron_wayland vivaldi-stable-alt
    just add_args vivaldi-stable-alt '"--profile-directory=Profile 1"'
    just add_name vivaldi-stable-alt "(test profile)"
    [[ -d "${HOME}/.config/vivaldi/Profile 1" ]] || rm vivaldi-stable-alt.desktop

steam-games:
    ./make_steam_desktop_files.py

update-cache:
    mimeo --user --update

clean:
    rm -rf bitwarden.desktop obsidian.desktop steam.desktop steam-native.desktop vivaldi-stable.desktop vivaldi-stable-alt.desktop \
        steamgame_*.desktop steam_icons/
