directory: ~/annex/music
library: ~/annex/music/.library
plugins:
  # - bandcamp
  - bpd
  - edit
  - fetchart
  - fish
  - fromfilename
  - info
  - mbsync
  - permissions
  - play
  - replaygain
  - web

ui:
  color: yes

replace:
  '[\\/]': _
  '^\.': _
  '[\x00-\x1f]': _
  '[<>"\?\*\|]': ''
  '\s*:\s+': ' - '
  '\.$': ''
  '\s+$': ''
  '^\s+': ''

bpd:
  host: 127.0.0.1
  port: 6600

paths:
  default: $albumartist/$year - $album%aunique{}/$track $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $artist - $title
  albumtype:bootleg: Bootlegs/$albumartist/$year - $album%aunique{}/$track $title
  albumtype:podcast: Podcasts/$album - $albumartist - $disc/$track $artist - $title

play:
  command: vlc --qt-start-minimized

replaygain:
  backend: gstreamer
