#!/bin/zsh

# Exit if any command fails
set -e

GITDIR=$HOME/mail/.notmuch/git
GITURL="insert-url-here"
HOST=$(hostname)

function do_merge() {
    echo "gitmuch: beginning merge..."
    if git merge -s recursive -X theirs origin/master; then
        echo "gitmuch: merge complete."
    else
        echo "gitmuch: manual intervention needed :/"
        git mergetool && git commit -m "Conflict merge on $HOST"
    fi
}

case "$1" in
    init)
        [[ ! -d "$GITDIR" ]] && mkdir -p "$GITDIR"
        cd "$GITDIR" && git init
        notmuch dump tags
        git add tags
        git commit -m "Initial dump on $HOST"
        git remote add origin "$GITURL"
        git config branch.master.remote origin
        git config branch.master.merge master
        ;;

    clone)
        git clone "$GITURL" "$GITDIR"
        ;;

    # Save local changes to Git repository
    save)
        cd "$GITDIR"
        notmuch dump tags
        git commit -a --dry-run >/dev/null && \
            git commit -a -m "Dump on $HOST"
        ;;

    # Load remote changes
    load)
        cd "$GITDIR"
        local localrev newrev tmpfile
        localrev=$(cat .git/refs/heads/master)

        # Try to do a fast-forward pull. If it does not, merge it with manual intervention.
        git pull --ff-only || do_merge
        newrev=$(cat .git/refs/heads/master)

        if [[ "$localrev" != "$newrev" ]]; then
            # There were changes: apply them to the DB
            tmpfile=$(mktemp)
            git diff '$localrev..$newrev' | grep '^+[^++ b/]' | cut -c 2- > "$tmpfile"
            notmuch restore "$tmpfile"
            rm "$tmpfile"
        fi
        ;;

    *)
        echo "Unknown command: $1"
        exit 1
esac
