#!/bin/zsh

. ~/.config/notmuch/hook-common.zsh

ret=0

# Sync messages with remote server and autotag
nosync $CONFIGDIR/nm-sync || (echo "Sync/autotag failed." && ret=1)

awesome_end_update 
dbus-send --session --dest="org.gnu.Emacs" "/org/gnu/Emacs" "org.gnu.Emacs.NotmuchNotify"
$CONFIGDIR/notify.py

exit $ret
