#!/usr/bin/env zsh

. ~/.config/notmuch/hook-common.zsh

notmuch new
new=$(notmuch count tag:new)
LD_PRELOAD=/usr/lib/nosync/nosync.so $CONFIGDIR/autotag.py || echo "Autotag failed."

awesome_end_update
dbus-send --session --dest="org.gnu.Emacs" "/org/gnu/Emacs" "org.gnu.Emacs.NotmuchNotify"
[[ $new > 0 ]] && $CONFIGDIR/notify.py

# Once in a while, sync CardDAV contacts
if [[ $(( $RANDOM % 20 )) == 0 ]]; then
    pycardsyncer
fi
