#!/bin/zsh

. ~/.config/notmuch/hook-common.zsh

awesome_begin_update

# Removes messages with the "deleted" tag
(( $(notmuch count tag:deleted) > 0 )) && (notmuch search --output=files tag:deleted | xargs -rd'\n' rm)

MAXLOGS=50
ret=0

# Rotate offlineimap logs
[[ -e "$CONFIGDIR/log/mail.$MAXLOGS.log" ]] && rm "$CONFIGDIR/log/mail.$MAXLOGS.log"
for ((i=$MAXLOGS-1; i >= 0; i--)); do
    j=$(( $i+1 ))
    [[ -e "$CONFIGDIR/log/mail.$i.log" ]] && mv "$CONFIGDIR/log/mail.$i.log" "$CONFIGDIR/log/mail.$j.log"
done

echo "Fetching mail..."
timeout -k 1m 4m offlineimap -o > "$CONFIGDIR/log/mail.0.log" || (echo "Fetch mail failed." && ret=1)
find ~/.offlineimap -type f -name '*.lock' -delete

exit $ret
