#!/bin/zsh

set -e

lastbak=$(ls -t ~/.config/notmuch/bak/db-*.xz | head -n1)

function nm_push() {
    ~/.config/notmuch/notmuch-incr-dump $lastbak 2>/dev/null | gzip | ssh kimsufi 'cat > notmuch.dump.gz'
}

function nm_get() {
    mailsync -b
    diff -u \
        <(~/.config/notmuch/notmuch-incr-dump $lastbak 2>/dev/null | sort) \
        <(ssh kimsufi 'cat notmuch.dump.gz' | zcat | sort) \
        |  awk '/^+/ && (NR>2) { print substr($0, 2)}' \
        | notmuch restore
}

case "$1" in
    "get"|"push")
        nm_$1
        exit $?
        ;;
    *)
        echo "Usage: $(basename $0) get|push"
        exit 1
esac
