function ltaai --wraps='eza $EXA_STANDARD_OPTIONS $EXA_LAAI_OPTIONS $EXA_LT_OPTIONS' --description 'alias ltaai eza $EXA_STANDARD_OPTIONS $EXA_LAAI_OPTIONS $EXA_LT_OPTIONS'
  eza $EXA_STANDARD_OPTIONS $EXA_LAAI_OPTIONS $EXA_LT_OPTIONS $argv
        
end
