#!/usr/bin/env python

from pathlib import Path
import random
import subprocess as subp

TRANSITION = "simple"
TRANSITION_SPEED = "50"

img_folder_txt = Path("~/.config/swww/images").expanduser().read_text().strip()
img_folder = Path(img_folder_txt).expanduser()

query_cp = subp.run(["swww", "query"], check=True, capture_output=True, text=True)
outputs = [line.split()[0].rstrip(":") for line in query_cp.stdout.splitlines()]

imgs = [img for img in img_folder.iterdir() if img.is_file()]
random.shuffle(imgs)

for out, img in zip(outputs, imgs):
    subp.run(
        [
            "swww",
            "img",
            "--transition-type",
            TRANSITION,
            "--transition-speed",
            TRANSITION_SPEED,
            "--outputs",
            out,
            img,
        ],
        check=True,
    )
