default: install-all

install NAME:
    @mkdir -p ~/.timewarrior/extensions
    ln -sf {{justfile_directory()}}/ext/{{NAME}}.* ~/.timewarrior/extensions/{{NAME}}

install-all: (install "pct_tags") (install "third_time")
