# -*- mode: sh; -*-

# Make sure profile (~/.zshenv) has been loaded
[[ -z "${PROFILE_LOADED}" ]] && . ~/.config/zsh/profile
unset PROFILE_LOADED

# Some environment variables may have already been reset by /etc/profile and friends.
. ~/.config/zsh/env

. ~/.config/zsh/aliases
. ~/.config/zsh/functions
. ~/.config/zsh/plugins
. ~/.config/zsh/keys

[[ -f ~/.config/zsh/private ]] && . ~/.config/zsh/private
