# -*- mode: sh; -*-

# Make sure profile (~/.zshenv) has been loaded
[[ -z "${PROFILE_LOADED}" ]] && . ~/.config/zsh/profile
unset PROFILE_LOADED

# Some environment variables may have already been reset by /etc/profile and friends.
. ~/.config/zsh/env

. ~/.config/zsh/aliases
. ~/.config/zsh/functions
. ~/.config/zsh/keys

. /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
